import type { Metadata } from "next";
import "@/styles/globals.css";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/toaster";
import AuthService from "@/services/auth.service";
import { Navbar } from "@/components/navigation/navbar";
import { redirect } from "next/navigation";
import { AuthComponent } from "@/components/navigation/auth-component";
import { Sidebar } from "@/components/navigation/sidebar";
import { AuthM } from "@/models/Auth";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const getData = async (): Promise<AuthM | null> => {
  const session = await new AuthService().getSession();
  console.log(session);

  return session ? session : null;
};

export default async function RootLayout({
  children,
  rider,
  stable,
}: // instructor,
{
  children: React.ReactNode;
  rider: React.ReactNode;
  stable: React.ReactNode;
  // instructor: React.ReactNode;
}) {
  const session = await getData();
  console.log(session);

  if (!session)
    return (
      <html lang="fr">
        <body
          className={cn(
            "min-h-screen font-sans antialiased w-full bg-foreground",
            fontSans.variable
          )}
        >
          <Navbar session={session} />
          <main className="flex items-center justify-center py-6 w-full">
            {children}
          </main>
          <Toaster />
        </body>
      </html>
    );

  return (
    <html lang="fr">
      <body
        className={cn(
          "min-h-screen font-sans antialiased w-full bg-foreground",
          fontSans.variable
        )}
      >
        <Navbar session={session} />
        <main className="flex min-h-screen  w-full">
          <Sidebar session={session} />
          <section className="p-4 w-full h-full overflow-y-auto">
            {session.role === "user"
              ? rider
              : session.role === "stable"
              ? stable
              : // : session.role === "instructor"
                // ? instructor
                null}
          </section>
        </main>
        <Toaster />
      </body>
    </html>
  );
}
